version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Jakarta"
    groups:
      composer-production:
        patterns:
          - "*"
        dependency-type: "production"
      composer-development:
        patterns:
          - "*"
        dependency-type: "development"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Jakarta"
    groups:
      npm-production:
        dependency-type: "production"
        patterns:
          - "*"
      npm-development:
        dependency-type: "development"
        patterns:
          - "*"
